ops:
  season_rankings_report_for_all:
    config:
      top_n: 5000
      start_date: 2025-11-03
      end_date: 2025-11-27
      simple: false
resources:
  database:
    config:
      database:
        env: DUCKDB_DATABASE
  storage:
    config:
      filepath:
        env: LOCAL_STORAGE_PATH
  templates:
    config:
      searchpath:
        env: JINJA_TEMPLATES_PATH

