ops:
  top_lines_html_table_for_all:
    config:
      top_n: 5000
      start_date: 2025-11-03
      end_date: 2025-11-04
resources:
  database:
    config:
      database:
        env: DUCKDB_DATABASE
  storage:
    config:
      filepath:
        env: LOCAL_STORAGE_PATH
  templates:
    config:
      searchpath:
        env: JINJA_TEMPLATES_PATH

